blank_issues_enabled: false
contact_links:
  - name: Vulnerability found
    url: https://github.com/sebsmgzz/IoTunas/security/policy
    about: Did you find a severe vulnerability? Please do NOT file a pubic issue. Take a look at our security policy.
  - name: Show and tell
    url: https://github.com/sebsmgzz/IIoTunas/discussions/new?category=show-and-tell
    about: Did you created a snippet or have something in mind that you want to share with us? Do it here.
  - name: Ask a question
    url: https://github.com/sebsmgzz/IIoTunas/discussions/new?category=q-a
    about: Please ask and answer questions under discussions Q&A.
