# Useful links:
#   Events: https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows
#   Environment: https://docs.github.com/en/actions/learn-github-actions/environment-variables
#   Webhooks: https://docs.github.com/en/developers/webhooks-and-events/webhooks/webhook-events-and-payloads

# Manages continuous integration of PRs into the develop branch
name: CI
on:
  push:
    branches:
    - develop
  pull_request:
    branches:
    - develop
jobs:

  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Build
      run: dotnet build --configuration Release src/IoTunas.Core
